# Feature Transformation with Amazon a SageMaker Processing Job and Scikit-Learn

In this notebook, we convert raw text into BERT embeddings.  This will allow us to perform natural language processing tasks such as text classification.

Typically a machine learning (ML) process consists of few steps. First, gathering data with various ETL jobs, then pre-processing the data, featurizing the dataset by incorporating standard techniques or prior knowledge, and finally training an ML model using an algorithm.

Often, distributed data processing frameworks such as Scikit-Learn are used to pre-process data sets in order to prepare them for training. In this notebook we'll use Amazon SageMaker Processing, and leverage the power of Scikit-Learn in a managed SageMaker environment to run our processing workload.

# NOTE:  THIS NOTEBOOK WILL TAKE A 5-10 MINUTES TO COMPLETE.

# PLEASE BE PATIENT.

![](img/prepare_dataset_bert.png)

![](img/processing.jpg)

## Contents

1. Setup Environment
1. Setup Input Data
1. Setup Output Data
1. Build a Scikit-Learn container for running the processing job
1. Run the Processing Job using Amazon SageMaker
1. Inspect the Processed Output Data

# Setup Environment

Let's start by specifying:
* The S3 bucket and prefixes that you use for training and model data. Use the default bucket specified by the Amazon SageMaker session.
* The IAM role ARN used to give processing and training access to the dataset.

In [1]:
import sagemaker
import boto3

sess = sagemaker.Session()
role = sagemaker.get_execution_role()
bucket = sess.default_bucket()
region = boto3.Session().region_name

sm = boto3.Session().client(service_name="sagemaker", region_name=region)
s3 = boto3.Session().client(service_name="s3", region_name=region)

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

# Setup Input Data

In [2]:
%store -r s3_public_path_tsv

In [3]:
try:
    s3_public_path_tsv
except NameError:
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the INGEST section before you continue.")
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

In [4]:
print(s3_public_path_tsv)

s3://dsoaws/amazon-reviews-pds/tsv

In [5]:
%store -r s3_private_path_tsv

In [6]:
try:
    s3_private_path_tsv
except NameError:
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("[ERROR] Please run the notebooks in the INGEST section before you continue.")
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

In [7]:
print(s3_private_path_tsv)

s3://sagemaker-us-east-1-891377026966/amazon-reviews-pds/tsv

In [8]:
raw_input_data_s3_uri = "s3://{}/amazon-reviews-pds/tsv/".format(bucket)
print(raw_input_data_s3_uri)

s3://sagemaker-us-east-1-891377026966/amazon-reviews-pds/tsv/

In [9]:
!aws s3 ls $raw_input_data_s3_uri

2024-06-30 23:46:40   18997559 amazon_reviews_us_Digital_Software_v1_00.tsv.gz
2024-06-30 23:46:42   27442648 amazon_reviews_us_Digital_Video_Games_v1_00.tsv.gz
2024-06-30 23:46:44   12134676 amazon_reviews_us_Gift_Card_v1_00.tsv.gz

# Run the Processing Job using Amazon SageMaker

Next, use the Amazon SageMaker Python SDK to submit a processing job using our custom python script.

# Review the Processing Script

In [10]:
!pygmentize preprocess-scikit-text-to-bert-feature-store.py

from sklearn.model_selection import train_test_split
from sklearn.utils import resample
import functools
import multiprocessing

from datetime import datetime
from time import gmtime, strftime, sleep

import sys
import re
import collections
import argparse
import json
import os
import csv
import glob
from pathlib import Path
import time
import boto3
import subprocess

## PIP INSTALLS ##
# This is 2.3.0 (vs. 2.3.1 everywhere else) because we need to
# use anaconda and anaconda only supports 2.3.0 at this time
#subprocess.check_call([sys.executable, "-m", "conda", "install", "-c", "anaconda", "tensorflow==2.3.0", "-y"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "tensorflow==2.3.1"])

import tensorflow as tf
from tensorflow import keras

subprocess.check_call([sys.executable, "-m", "conda", "install", "-c", "conda-forge", "transformers==3.5.1", "-y"])
from transformers import DistilBertTokenizer
from transformers import DistilBertConfig

#subprocess.check_call([sys.executable, "-m", "pip", "install", "sagemaker==2.24.1"])
import pandas as pd
import re
# import sagemaker
# from sagemaker.session import Session
# from sagemaker.feature_store.feature_group import FeatureGroup
# from sagemaker.feature_store.feature_definition import (
#     FeatureDefinition,
#     FeatureTypeEnum,
# )

# region = os.environ["AWS_DEFAULT_REGION"]
# print("Region: {}".format(region))

# #############################
# ## We may need to get the Role and Bucket before setting sm, featurestore_runtime, etc.
# ## Role and Bucket are malformed if we do this later.
# sts = boto3.Session(region_name=region).client(service_name="sts", region_name=region)

# caller_identity = sts.get_caller_identity()
# print("caller_identity: {}".format(caller_identity))

# assumed_role_arn = caller_identity["Arn"]
# print("(assumed_role) caller_identity_arn: {}".format(assumed_role_arn))

# assumed_role_name = assumed_role_arn.split("/")[-2]

# iam = boto3.Session(region_name=region).client(service_name="iam", region_name=region)
# get_role_response = iam.get_role(RoleName=assumed_role_name)
# print("get_role_response {}".format(get_role_response))
# role = get_role_response["Role"]["Arn"]
# print("role {}".format(role))

# bucket = sagemaker.Session().default_bucket()
# print("The DEFAULT BUCKET is {}".format(bucket))
# #############################

# sm = boto3.Session(region_name=region).client(service_name="sagemaker", region_name=region)

# featurestore_runtime = boto3.Session(region_name=region).client(
#     service_name="sagemaker-featurestore-runtime", region_name=region
# )

# s3 = boto3.Session(region_name=region).client(service_name="s3", region_name=region)

# sagemaker_session = sagemaker.Session(
#     boto_session=boto3.Session(region_name=region),
#     sagemaker_client=sm,
#     sagemaker_featurestore_runtime_client=featurestore_runtime,
# )

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

REVIEW_BODY_COLUMN = "review_body"
REVIEW_ID_COLUMN = "review_id"
# DATE_COLUMN = 'date'

LABEL_COLUMN = "star_rating"
LABEL_VALUES = [1, 2, 3, 4, 5]

label_map = {}
for (i, label) in enumerate(LABEL_VALUES):
    label_map[label] = i


def cast_object_to_string(data_frame):
    for label in data_frame.columns:
        if data_frame.dtypes[label] == "object":
            data_frame[label] = data_frame[label].astype("str").astype("string")
    return data_frame


# def wait_for_feature_group_creation_complete(feature_group):
#     try:
#         status = feature_group.describe().get("FeatureGroupStatus")
#         print("Feature Group status: {}".format(status))
#         while status == "Creating":
#             print("Waiting for Feature Group Creation")
#             time.sleep(5)
#             status = feature_group.describe().get("FeatureGroupStatus")
#             print("Feature Group status: {}".format(status))
#         if status != "Created":
#             print("Feature Group status: {}".format(status))
#             raise RuntimeError(f"Failed to create feature group {feature_group.name}")
#         print(f"FeatureGroup {feature_group.name} successfully created.")
#     except:
#         print("No feature group created yet.")


# def create_or_load_feature_group(prefix, feature_group_name):

#     # Feature Definitions for our records
#     feature_definitions = [
#         FeatureDefinition(feature_name="input_ids", feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="input_mask", feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="segment_ids", feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="label_id", feature_type=FeatureTypeEnum.INTEGRAL),
#         FeatureDefinition(feature_name="review_id", feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="date", feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="label", feature_type=FeatureTypeEnum.INTEGRAL),
#         #        FeatureDefinition(feature_name='review_body', feature_type=FeatureTypeEnum.STRING),
#         FeatureDefinition(feature_name="split_type", feature_type=FeatureTypeEnum.STRING),
#     ]

#     feature_group = FeatureGroup(
#         name=feature_group_name, feature_definitions=feature_definitions, sagemaker_session=sagemaker_session
#     )

#     print("Feature Group: {}".format(feature_group))

#     try:
#         print(
#             "Waiting for existing Feature Group to become available if it is being created by another instance in our cluster..."
#         )
#         wait_for_feature_group_creation_complete(feature_group)
#     except Exception as e:
#         print("Before CREATE FG wait exeption: {}".format(e))
#     #        pass

#     try:
#         record_identifier_feature_name = "review_id"
#         event_time_feature_name = "date"

#         print("Creating Feature Group with role {}...".format(role))
#         feature_group.create(
#             s3_uri=f"s3://{bucket}/{prefix}",
#             record_identifier_name=record_identifier_feature_name,
#             event_time_feature_name=event_time_feature_name,
#             role_arn=role,
#             enable_online_store=False,
#         )
#         print("Creating Feature Group. Completed.")

#         print("Waiting for new Feature Group to become available...")
#         wait_for_feature_group_creation_complete(feature_group)
#         print("Feature Group available.")
#         feature_group.describe()

#     except Exception as e:
#         print("Exception: {}".format(e))

#     return feature_group


class InputFeatures(object):
    """BERT feature vectors."""

    def __init__(self, input_ids, input_mask, segment_ids, label_id, review_id, date, label):
        #               review_body):
        self.input_ids = input_ids
        self.input_mask = input_mask
        self.segment_ids = segment_ids
        self.label_id = label_id
        self.review_id = review_id
        self.date = date
        self.label = label


#        self.review_body = review_body


class Input(object):
    """A single training/test input for sequence classification."""

    def __init__(self, text, review_id, date, label=None):
        """Constructs an Input.
        Args:
          text: string. The untokenized text of the first sequence. For single
            sequence tasks, only this sequence must be specified.
          label: (Optional) string. The label of the example. This should be
            specified for train and dev examples, but not for test examples.
        """
        self.text = text
        self.review_id = review_id
        self.date = date
        self.label = label


def convert_input(the_input, max_seq_length):
    # First, we need to preprocess our data so that it matches the data BERT was trained on:
    #
    # 1. Lowercase our text (if we're using a BERT lowercase model)
    # 2. Tokenize it (i.e. "sally says hi" -> ["sally", "says", "hi"])
    # 3. Break words into WordPieces (i.e. "calling" -> ["call", "##ing"])
    #
    # Fortunately, the Transformers tokenizer does this for us!
    #
    tokens = tokenizer.tokenize(the_input.text)

    # Next, we need to do the following:
    #
    # 4. Map our words to indexes using a vocab file that BERT provides
    # 5. Add special "CLS" and "SEP" tokens (see the [readme](https://github.com/google-research/bert))
    # 6. Append "index" and "segment" tokens to each input (see the [BERT paper](https://arxiv.org/pdf/1810.04805.pdf))
    #
    # Again, the Transformers tokenizer does this for us!
    #
    encode_plus_tokens = tokenizer.encode_plus(
        the_input.text,
        padding='max_length',
        max_length=max_seq_length,
        truncation=True
    )

    # The id from the pre-trained BERT vocabulary that represents the token.  (Padding of 0 will be used if the # of tokens is less than `max_seq_length`)
    input_ids = encode_plus_tokens["input_ids"]

    # Specifies which tokens BERT should pay attention to (0 or 1).  Padded `input_ids` will have 0 in each of these vector elements.
    input_mask = encode_plus_tokens["attention_mask"]

    # Segment ids are always 0 for single-sequence tasks such as text classification.  1 is used for two-sequence tasks such as question/answer and next sentence prediction.
    segment_ids = [0] * max_seq_length

    # Label for each training row (`star_rating` 1 through 5)
    label_id = label_map[the_input.label]

    features = InputFeatures(
        input_ids=input_ids,
        input_mask=input_mask,
        segment_ids=segment_ids,
        label_id=label_id,
        review_id=the_input.review_id,
        date=the_input.date,
        label=the_input.label,
    )
    #        review_body=the_input.text)

    #     print('**input_ids**\n{}\n'.format(features.input_ids))
    #     print('**input_mask**\n{}\n'.format(features.input_mask))
    #     print('**segment_ids**\n{}\n'.format(features.segment_ids))
    #     print('**label_id**\n{}\n'.format(features.label_id))
    #     print('**review_id**\n{}\n'.format(features.review_id))
    #     print('**date**\n{}\n'.format(features.date))
    #     print('**label**\n{}\n'.format(features.label))
    #    print('**review_body**\n{}\n'.format(features.review_body))

    return features


def transform_inputs_to_tfrecord(inputs, output_file, max_seq_length):
    """Convert a set of `Input`s to a TFRecord file."""

    records = []

    tf_record_writer = tf.io.TFRecordWriter(output_file)

    for (input_idx, the_input) in enumerate(inputs):
        if input_idx % 10000 == 0:
            print("Writing input {} of {}\n".format(input_idx, len(inputs)))

        features = convert_input(the_input, max_seq_length)

        all_features = collections.OrderedDict()
        all_features["input_ids"] = tf.train.Feature(int64_list=tf.train.Int64List(value=features.input_ids))
        all_features["input_mask"] = tf.train.Feature(int64_list=tf.train.Int64List(value=features.input_mask))
        all_features["segment_ids"] = tf.train.Feature(int64_list=tf.train.Int64List(value=features.segment_ids))
        all_features["label_ids"] = tf.train.Feature(int64_list=tf.train.Int64List(value=[features.label_id]))

        tf_record = tf.train.Example(features=tf.train.Features(feature=all_features))
        tf_record_writer.write(tf_record.SerializeToString())

        records.append(
            {  #'tf_record': tf_record.SerializeToString(),
                "input_ids": features.input_ids,
                "input_mask": features.input_mask,
                "segment_ids": features.segment_ids,
                "label_id": features.label_id,
                "review_id": the_input.review_id,
                "date": the_input.date,
                "label": features.label,
                #                        'review_body': features.review_body
            }
        )

        #####################################
        ####### TODO:  REMOVE THIS BREAK #######
        #####################################
        # break

    tf_record_writer.close()

    return records


def list_arg(raw_value):
    """argparse type for a list of strings"""
    return str(raw_value).split(",")


def parse_args():
    # Unlike SageMaker training jobs (which have `SM_HOSTS` and `SM_CURRENT_HOST` env vars), processing jobs to need to parse the resource config file directly
    resconfig = {}
    try:
        with open("/opt/ml/config/resourceconfig.json", "r") as cfgfile:
            resconfig = json.load(cfgfile)
    except FileNotFoundError:
        print("/opt/ml/config/resourceconfig.json not found.  current_host is unknown.")
        pass  # Ignore

    # Local testing with CLI args
    parser = argparse.ArgumentParser(description="Process")

    parser.add_argument(
        "--hosts",
        type=list_arg,
        default=resconfig.get("hosts", ["unknown"]),
        help="Comma-separated list of host names running the job",
    )
    parser.add_argument(
        "--current-host",
        type=str,
        default=resconfig.get("current_host", "unknown"),
        help="Name of this host running the job",
    )
    parser.add_argument(
        "--input-data",
        type=str,
        default="/opt/ml/processing/input/data",
    )
    parser.add_argument(
        "--output-data",
        type=str,
        default="/opt/ml/processing/output",
    )
    parser.add_argument(
        "--train-split-percentage",
        type=float,
        default=0.90,
    )
    parser.add_argument(
        "--validation-split-percentage",
        type=float,
        default=0.05,
    )
    parser.add_argument(
        "--test-split-percentage",
        type=float,
        default=0.05,
    )
    parser.add_argument("--balance-dataset", type=eval, default=True)
    parser.add_argument(
        "--max-seq-length",
        type=int,
        default=64,
    )
    parser.add_argument(
        "--feature-store-offline-prefix",
        type=str,
        default=None,
    )
    parser.add_argument(
        "--feature-group-name",
        type=str,
        default=None,
    )

    return parser.parse_args()


def _transform_tsv_to_tfrecord(file, max_seq_length, balance_dataset, prefix, feature_group_name):
    print("file {}".format(file))
    print("max_seq_length {}".format(max_seq_length))
    print("balance_dataset {}".format(balance_dataset))
    print("prefix {}".format(prefix))
    print("feature_group_name {}".format(feature_group_name))

    # need to re-load since we can't pass feature_group object in _partial functions for some reason
#    feature_group = create_or_load_feature_group(prefix, feature_group_name)

    filename_without_extension = Path(Path(file).stem).stem

    df = pd.read_csv(file, delimiter="\t", quoting=csv.QUOTE_NONE, compression="gzip")

    df.isna().values.any()
    df = df.dropna()
    df = df.reset_index(drop=True)

    print("Shape of dataframe {}".format(df.shape))

    if balance_dataset:
        # Balance the dataset down to the minority class
        df_grouped_by = df.groupby(["star_rating"])
        df_balanced = df_grouped_by.apply(lambda x: x.sample(df_grouped_by.size().min()).reset_index(drop=True))

        df_balanced = df_balanced.reset_index(drop=True)
        print("Shape of balanced dataframe {}".format(df_balanced.shape))

        print(df_balanced["star_rating"].head(100))

        df = df_balanced

    print("Shape of dataframe before splitting {}".format(df.shape))

    print("train split percentage {}".format(args.train_split_percentage))
    print("validation split percentage {}".format(args.validation_split_percentage))
    print("test split percentage {}".format(args.test_split_percentage))

    holdout_percentage = 1.00 - args.train_split_percentage
    print("holdout percentage {}".format(holdout_percentage))

    df_train, df_holdout = train_test_split(df, test_size=holdout_percentage, stratify=df["star_rating"])

    test_holdout_percentage = args.test_split_percentage / holdout_percentage

    print("test holdout percentage {}".format(test_holdout_percentage))

    df_validation, df_test = train_test_split(
        df_holdout, test_size=test_holdout_percentage, stratify=df_holdout["star_rating"])

    df_train = df_train.reset_index(drop=True)
    df_validation = df_validation.reset_index(drop=True)
    df_test = df_test.reset_index(drop=True)

    print("Shape of train dataframe {}".format(df_train.shape))
    print("Shape of validation dataframe {}".format(df_validation.shape))
    print("Shape of test dataframe {}".format(df_test.shape))

    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
    print(timestamp)

    train_inputs = df_train.apply(
        lambda x: Input(
            label=x[LABEL_COLUMN], text=x[REVIEW_BODY_COLUMN], review_id=x[REVIEW_ID_COLUMN], date=timestamp
        ),
        axis=1,
    )

    validation_inputs = df_validation.apply(
        lambda x: Input(
            label=x[LABEL_COLUMN], text=x[REVIEW_BODY_COLUMN], review_id=x[REVIEW_ID_COLUMN], date=timestamp
        ),
        axis=1,
    )

    test_inputs = df_test.apply(
        lambda x: Input(
            label=x[LABEL_COLUMN], text=x[REVIEW_BODY_COLUMN], review_id=x[REVIEW_ID_COLUMN], date=timestamp
        ),
        axis=1,
    )

    # Next, we need to preprocess our data so that it matches the data BERT was trained on. For this, we'll need to do a couple of things (but don't worry--this is also included in the Python library):
    #
    #
    # 1. Lowercase our text (if we're using a BERT lowercase model)
    # 2. Tokenize it (i.e. "sally says hi" -> ["sally", "says", "hi"])
    # 3. Break words into WordPieces (i.e. "calling" -> ["call", "##ing"])
    # 4. Map our words to indexes using a vocab file that BERT provides
    # 5. Add special "CLS" and "SEP" tokens (see the [readme](https://github.com/google-research/bert))
    # 6. Append "index" and "segment" tokens to each input (see the [BERT paper](https://arxiv.org/pdf/1810.04805.pdf))
    #
    # We don't have to worry about these details.  The Transformers tokenizer does this for us.
    #
    train_data = "{}/bert/train".format(args.output_data)
    validation_data = "{}/bert/validation".format(args.output_data)
    test_data = "{}/bert/test".format(args.output_data)

    # Convert our train and validation features to InputFeatures (.tfrecord protobuf) that works with BERT and TensorFlow.
    train_records = transform_inputs_to_tfrecord(
        train_inputs,
        "{}/part-{}-{}.tfrecord".format(train_data, args.current_host, filename_without_extension),
        max_seq_length,
    )

    validation_records = transform_inputs_to_tfrecord(
        validation_inputs,
        "{}/part-{}-{}.tfrecord".format(validation_data, args.current_host, filename_without_extension),
        max_seq_length,
    )

    test_records = transform_inputs_to_tfrecord(
        test_inputs,
        "{}/part-{}-{}.tfrecord".format(test_data, args.current_host, filename_without_extension),
        max_seq_length,
    )

    df_train_records = pd.DataFrame.from_dict(train_records)
    df_train_records["split_type"] = "train"
    df_train_records.head()

    df_validation_records = pd.DataFrame.from_dict(validation_records)
    df_validation_records["split_type"] = "validation"
    df_validation_records.head()

    df_test_records = pd.DataFrame.from_dict(test_records)
    df_test_records["split_type"] = "test"
    df_test_records.head()

    # Add record to feature store
#     df_fs_train_records = cast_object_to_string(df_train_records)
#     df_fs_validation_records = cast_object_to_string(df_validation_records)
#     df_fs_test_records = cast_object_to_string(df_test_records)

#     print("Ingesting features...")
#     feature_group.ingest(data_frame=df_fs_train_records, max_workers=3, wait=True)
#     feature_group.ingest(data_frame=df_fs_validation_records, max_workers=3, wait=True)

Run this script as a processing job.  You also need to specify one `ProcessingInput` with the `source` argument of the Amazon S3 bucket and `destination` is where the script reads this data from `/opt/ml/processing/input` (inside the Docker container.)  All local paths inside the processing container must begin with `/opt/ml/processing/`.

Also give the `run()` method a `ProcessingOutput`, where the `source` is the path the script writes output data to.  For outputs, the `destination` defaults to an S3 bucket that the Amazon SageMaker Python SDK creates for you, following the format `s3://sagemaker-<region>-<account_id>/<processing_job_name>/output/<output_name>/`.  You also give the `ProcessingOutput` value for `output_name`, to make it easier to retrieve these output artifacts after the job is run.

The arguments parameter in the `run()` method are command-line arguments in our `preprocess-scikit-text-to-bert-feature-store.py` script.

Note that we sharding the data using `ShardedByS3Key` to spread the transformations across all worker nodes in the cluster.

# Track the `Experiment`
We will track every step of this experiment throughout the `prepare`, `train`, `optimize`, and `deploy`.

# Concepts

**Experiment**: A collection of related Trials.  Add Trials to an Experiment that you wish to compare together.

**Trial**: A description of a multi-step machine learning workflow. Each step in the workflow is described by a Trial Component. There is no relationship between Trial Components such as ordering.

**Trial Component**: A description of a single step in a machine learning workflow. For example data cleaning, feature extraction, model training, model evaluation, etc.

**Tracker**: A logger of information about a single TrialComponent.

<img src="img/sagemaker-experiments.png" width="90%" align="left">

# Create the `Experiment`

In [15]:
!pip install sagemaker-experiments

Collecting sagemaker-experiments
  Downloading sagemaker_experiments-0.1.45-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: boto3>=1.16.27 in /opt/conda/lib/python3.10/site-packages (from sagemaker-experiments) (1.34.51)
Requirement already satisfied: botocore<1.35.0,>=1.34.51 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (1.34.51)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /opt/conda/lib/python3.10/site-packages (from boto3>=1.16.27->sagemaker-experiments) (0.10.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.10/site-packages (from botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (2.9.0)
Requirement already satisfied: urllib3<2.1,>=1.25.4 in /opt/conda/lib/python3.10/site-packages (from botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (1.26.18)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.35.0,>=1.34.51->boto3>=1.16.27->sagemaker-experiments) (1.16.0)
Downloading sagemaker_experiments-0.1.45-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 5.6 MB/s eta 0:00:00
Installing collected packages: sagemaker-experiments
Successfully installed sagemaker-experiments-0.1.45

In [16]:
import time
from smexperiments.experiment import Experiment

timestamp = int(time.time())

experiment = Experiment.create(
    experiment_name="Amazon-Customer-Reviews-BERT-Experiment-{}".format(timestamp),
    description="Amazon Customer Reviews BERT Experiment",
    sagemaker_boto_client=sm,
)

experiment_name = experiment.experiment_name
print("Experiment name: {}".format(experiment_name))

Experiment name: Amazon-Customer-Reviews-BERT-Experiment-1719873607

# Create the `Trial`

In [17]:
import time
from smexperiments.trial import Trial

timestamp = int(time.time())

trial = Trial.create(
    trial_name="trial-{}".format(timestamp), experiment_name=experiment_name, sagemaker_boto_client=sm
)

trial_name = trial.trial_name
print("Trial name: {}".format(trial_name))

Trial name: trial-1719873613

# Create the `Experiment Config`

In [18]:
experiment_config = {
    "ExperimentName": experiment_name,
    "TrialName": trial_name,
    "TrialComponentDisplayName": "prepare",
}

In [19]:
print(experiment_name)

Amazon-Customer-Reviews-BERT-Experiment-1719873607

In [20]:
%store experiment_name

Stored 'experiment_name' (str)

In [21]:
print(trial_name)

trial-1719873613

In [22]:
%store trial_name

Stored 'trial_name' (str)

# Create Feature Store and Feature Group

In [23]:
featurestore_runtime = boto3.Session().client(service_name="sagemaker-featurestore-runtime", region_name=region)

In [24]:
timestamp = int(time.time())

feature_store_offline_prefix = "reviews-feature-store-" + str(timestamp)

print(feature_store_offline_prefix)

reviews-feature-store-1719873648

In [25]:
feature_group_name = "reviews-feature-group-" + str(timestamp)

print(feature_group_name)

reviews-feature-group-1719873648

In [26]:
from sagemaker.feature_store.feature_definition import (
    FeatureDefinition,
    FeatureTypeEnum,
)

feature_definitions = [
    FeatureDefinition(feature_name="input_ids", feature_type=FeatureTypeEnum.STRING),
    FeatureDefinition(feature_name="input_mask", feature_type=FeatureTypeEnum.STRING),
    FeatureDefinition(feature_name="segment_ids", feature_type=FeatureTypeEnum.STRING),
    FeatureDefinition(feature_name="label_id", feature_type=FeatureTypeEnum.INTEGRAL),
    FeatureDefinition(feature_name="review_id", feature_type=FeatureTypeEnum.STRING),
    FeatureDefinition(feature_name="date", feature_type=FeatureTypeEnum.STRING),
    FeatureDefinition(feature_name="label", feature_type=FeatureTypeEnum.INTEGRAL),
    #    FeatureDefinition(feature_name='review_body', feature_type=FeatureTypeEnum.STRING)
]

In [27]:
from sagemaker.feature_store.feature_group import FeatureGroup

feature_group = FeatureGroup(name=feature_group_name, feature_definitions=feature_definitions, sagemaker_session=sess)

print(feature_group)

FeatureGroup(name='reviews-feature-group-1719873648', sagemaker_session=<sagemaker.session.Session object at 0x7f1387b17100>, feature_definitions=[FeatureDefinition(feature_name='input_ids', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None), FeatureDefinition(feature_name='input_mask', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None), FeatureDefinition(feature_name='segment_ids', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None), FeatureDefinition(feature_name='label_id', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None), FeatureDefinition(feature_name='review_id', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None), FeatureDefinition(feature_name='date', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None), FeatureDefinition(feature_name='label', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None)])

# Set the Processing Job Hyper-Parameters

In [31]:
processing_instance_type = "ml.t3.xlarge"
processing_instance_count = 2
train_split_percentage = 0.90
validation_split_percentage = 0.05
test_split_percentage = 0.05
balance_dataset = True
max_seq_length = 64

# Choosing a `max_seq_length` for BERT
Since a smaller `max_seq_length` leads to faster training and lower resource utilization, we want to find the smallest review length that captures `80%` of our reviews.

Remember our distribution of review lengths from a previous section?

```
mean         51.683405
std         107.030844
min           1.000000
10%           2.000000
20%           7.000000
30%          19.000000
40%          22.000000
50%          26.000000
60%          32.000000
70%          43.000000
80%          63.000000
90%         110.000000
100%       5347.000000
max        5347.000000
```

![](img/review_word_count_distribution.png)

Review length `63` represents the `80th` percentile for this dataset.  However, it's best to stick with powers-of-2 when using BERT.  So let's choose `64` as this is the smallest power-of-2 greater than `63`.  Reviews with length > `64` will be truncated to `64`.

In [32]:
from sagemaker.sklearn.processing import SKLearnProcessor

processor = SKLearnProcessor(
    framework_version="0.23-1",
    role=role,
    instance_type=processing_instance_type,
    instance_count=processing_instance_count,
    env={"AWS_DEFAULT_REGION": region},
    max_runtime_in_seconds=7200,
)

INFO:sagemaker.image_uris:Defaulting to only available Python version: py3

In [33]:
from sagemaker.processing import ProcessingInput, ProcessingOutput

processor.run(
    code="preprocess-scikit-text-to-bert-feature-store.py",
    inputs=[
        ProcessingInput(
            input_name="raw-input-data",
            source=raw_input_data_s3_uri,
            destination="/opt/ml/processing/input/data/",
            s3_data_distribution_type="ShardedByS3Key",
        )
    ],
    outputs=[
        ProcessingOutput(
            output_name="bert-train", s3_upload_mode="EndOfJob", source="/opt/ml/processing/output/bert/train"
        ),
        ProcessingOutput(
            output_name="bert-validation",
            s3_upload_mode="EndOfJob",
            source="/opt/ml/processing/output/bert/validation",
        ),
        ProcessingOutput(
            output_name="bert-test", s3_upload_mode="EndOfJob", source="/opt/ml/processing/output/bert/test"
        ),
    ],
    arguments=[
        "--train-split-percentage",
        str(train_split_percentage),
        "--validation-split-percentage",
        str(validation_split_percentage),
        "--test-split-percentage",
        str(test_split_percentage),
        "--max-seq-length",
        str(max_seq_length),
        "--balance-dataset",
        str(balance_dataset),
        "--feature-store-offline-prefix",
        str(feature_store_offline_prefix),
        "--feature-group-name",
        str(feature_group_name),
    ],
    experiment_config=experiment_config,
    logs=True,
    wait=False,
)

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2024-07-01-22-42-17-522

In [34]:
scikit_processing_job_name = processor.jobs[-1].describe()["ProcessingJobName"]
print(scikit_processing_job_name)

sagemaker-scikit-learn-2024-07-01-22-42-17-522

In [35]:
from IPython.core.display import display, HTML

display(
    HTML(
        '<b>Review <a target="blank" href="https://console.aws.amazon.com/sagemaker/home?region={}#/processing-jobs/{}">Processing Job</a></b>'.format(
            region, scikit_processing_job_name
        )
    )
)

/tmp/ipykernel_1088/1926661146.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [36]:
from IPython.core.display import display, HTML

display(
    HTML(
        '<b>Review <a target="blank" href="https://console.aws.amazon.com/cloudwatch/home?region={}#logStream:group=/aws/sagemaker/ProcessingJobs;prefix={};streamFilter=typeLogStreamPrefix">CloudWatch Logs</a> After About 5 Minutes</b>'.format(
            region, scikit_processing_job_name
        )
    )
)

/tmp/ipykernel_1088/267036670.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [37]:
from IPython.core.display import display, HTML

display(
    HTML(
        '<b>Review <a target="blank" href="https://s3.console.aws.amazon.com/s3/buckets/{}/{}/?region={}&tab=overview">S3 Output Data</a> After The Processing Job Has Completed</b>'.format(
            bucket, scikit_processing_job_name, region
        )
    )
)

/tmp/ipykernel_1088/2163845711.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

# Monitor the Processing Job

In [38]:
running_processor = sagemaker.processing.ProcessingJob.from_processing_name(
    processing_job_name=scikit_processing_job_name, sagemaker_session=sess
)

processing_job_description = running_processor.describe()

print(processing_job_description)

{'ProcessingInputs': [{'InputName': 'raw-input-data', 'AppManaged': False, 'S3Input': {'S3Uri': 's3://sagemaker-us-east-1-891377026966/amazon-reviews-pds/tsv/', 'LocalPath': '/opt/ml/processing/input/data/', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3DataDistributionType': 'ShardedByS3Key', 'S3CompressionType': 'None'}}, {'InputName': 'code', 'AppManaged': False, 'S3Input': {'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/input/code/preprocess-scikit-text-to-bert-feature-store.py', 'LocalPath': '/opt/ml/processing/input/code', 'S3DataType': 'S3Prefix', 'S3InputMode': 'File', 'S3DataDistributionType': 'FullyReplicated', 'S3CompressionType': 'None'}}], 'ProcessingOutputConfig': {'Outputs': [{'OutputName': 'bert-train', 'S3Output': {'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train', 'LocalPath': '/opt/ml/processing/output/bert/train', 'S3UploadMode': 'EndOfJob'}, 'AppManaged': False}, {'OutputName': 'bert-validation', 'S3Output': {'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation', 'LocalPath': '/opt/ml/processing/output/bert/validation', 'S3UploadMode': 'EndOfJob'}, 'AppManaged': False}, {'OutputName': 'bert-test', 'S3Output': {'S3Uri': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test', 'LocalPath': '/opt/ml/processing/output/bert/test', 'S3UploadMode': 'EndOfJob'}, 'AppManaged': False}]}, 'ProcessingJobName': 'sagemaker-scikit-learn-2024-07-01-22-42-17-522', 'ProcessingResources': {'ClusterConfig': {'InstanceCount': 2, 'InstanceType': 'ml.t3.xlarge', 'VolumeSizeInGB': 30}}, 'StoppingCondition': {'MaxRuntimeInSeconds': 7200}, 'AppSpecification': {'ImageUri': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3', 'ContainerEntrypoint': ['python3', '/opt/ml/processing/input/code/preprocess-scikit-text-to-bert-feature-store.py'], 'ContainerArguments': ['--train-split-percentage', '0.9', '--validation-split-percentage', '0.05', '--test-split-percentage', '0.05', '--max-seq-length', '64', '--balance-dataset', 'True', '--feature-store-offline-prefix', 'reviews-feature-store-1719873648', '--feature-group-name', 'reviews-feature-group-1719873648']}, 'Environment': {'AWS_DEFAULT_REGION': 'us-east-1'}, 'RoleArn': 'arn:aws:iam::891377026966:role/service-role/AmazonSageMaker-ExecutionRole-20240628T190970', 'ExperimentConfig': {'ExperimentName': 'Amazon-Customer-Reviews-BERT-Experiment-1719873607', 'TrialName': 'trial-1719873613', 'TrialComponentDisplayName': 'prepare'}, 'ProcessingJobArn': 'arn:aws:sagemaker:us-east-1:891377026966:processing-job/sagemaker-scikit-learn-2024-07-01-22-42-17-522', 'ProcessingJobStatus': 'InProgress', 'LastModifiedTime': datetime.datetime(2024, 7, 1, 22, 42, 18, 586000, tzinfo=tzlocal()), 'CreationTime': datetime.datetime(2024, 7, 1, 22, 42, 17, 977000, tzinfo=tzlocal()), 'ResponseMetadata': {'RequestId': 'f43326b2-c817-4a5d-b149-eba8d52efe75', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f43326b2-c817-4a5d-b149-eba8d52efe75', 'content-type': 'application/x-amz-json-1.1', 'content-length': '2981', 'date': 'Mon, 01 Jul 2024 22:42:46 GMT'}, 'RetryAttempts': 0}}

In [39]:
running_processor.wait(logs=False)

....................................................................................................................................................................................................................!

# _Please Wait Until the ^^ Processing Job ^^ Completes Above._

# Inspect the Processed Output Data

Take a look at a few rows of the transformed dataset to make sure the processing was successful.

In [40]:
processing_job_description = running_processor.describe()

output_config = processing_job_description["ProcessingOutputConfig"]
for output in output_config["Outputs"]:
    if output["OutputName"] == "bert-train":
        processed_train_data_s3_uri = output["S3Output"]["S3Uri"]
    if output["OutputName"] == "bert-validation":
        processed_validation_data_s3_uri = output["S3Output"]["S3Uri"]
    if output["OutputName"] == "bert-test":
        processed_test_data_s3_uri = output["S3Output"]["S3Uri"]

print(processed_train_data_s3_uri)
print(processed_validation_data_s3_uri)
print(processed_test_data_s3_uri)

s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train
s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation
s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test

In [41]:
!aws s3 ls $processed_train_data_s3_uri/

2024-07-01 23:00:11   10472476 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11    2313178 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:36   11711096 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

In [42]:
!aws s3 ls $processed_validation_data_s3_uri/

2024-07-01 23:00:11     582429 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11     128035 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:36     651681 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

In [43]:
!aws s3 ls $processed_test_data_s3_uri/

2024-07-01 23:00:11     582260 part-algo-1-amazon_reviews_us_Digital_Software_v1_00.tfrecord
2024-07-01 23:00:11     128809 part-algo-1-amazon_reviews_us_Gift_Card_v1_00.tfrecord
2024-07-01 23:00:37     650896 part-algo-2-amazon_reviews_us_Digital_Video_Games_v1_00.tfrecord

# Pass Variables to the Next Notebook(s)

In [44]:
%store raw_input_data_s3_uri

Stored 'raw_input_data_s3_uri' (str)

In [45]:
%store max_seq_length

Stored 'max_seq_length' (int)

In [46]:
%store train_split_percentage

Stored 'train_split_percentage' (float)

In [47]:
%store validation_split_percentage

Stored 'validation_split_percentage' (float)

In [48]:
%store test_split_percentage

Stored 'test_split_percentage' (float)

In [49]:
%store balance_dataset

Stored 'balance_dataset' (bool)

In [50]:
%store feature_store_offline_prefix

Stored 'feature_store_offline_prefix' (str)

In [51]:
%store feature_group_name

Stored 'feature_group_name' (str)

In [52]:
%store processed_train_data_s3_uri

Stored 'processed_train_data_s3_uri' (str)

In [53]:
%store processed_validation_data_s3_uri

Stored 'processed_validation_data_s3_uri' (str)

In [54]:
%store processed_test_data_s3_uri

Stored 'processed_test_data_s3_uri' (str)

In [55]:
%store

Stored variables and their in-db values:
balance_dataset                                       -> True
balanced_bias_data_jsonlines_s3_uri                   -> 's3://sagemaker-us-east-1-891377026966/bias-detect
balanced_bias_data_s3_uri                             -> 's3://sagemaker-us-east-1-891377026966/bias-detect
bias_data_s3_uri                                      -> 's3://sagemaker-us-east-1-891377026966/bias-detect
experiment_name                                       -> 'Amazon-Customer-Reviews-BERT-Experiment-171987360
feature_group_name                                    -> 'reviews-feature-group-1719873648'
feature_store_offline_prefix                          -> 'reviews-feature-store-1719873648'
ingest_create_athena_db_passed                        -> True
ingest_create_athena_table_parquet_passed             -> True
ingest_create_athena_table_tsv_passed                 -> True
max_seq_length                                        -> 64
processed_test_data_s3_uri                            -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processed_train_data_s3_uri                           -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
processed_validation_data_s3_uri                      -> 's3://sagemaker-us-east-1-891377026966/sagemaker-s
raw_input_data_s3_uri                                 -> 's3://sagemaker-us-east-1-891377026966/amazon-revi
s3_private_path_tsv                                   -> 's3://sagemaker-us-east-1-891377026966/amazon-revi
s3_public_path_tsv                                    -> 's3://dsoaws/amazon-reviews-pds/tsv'
test_split_percentage                                 -> 0.05
train_split_percentage                                -> 0.9
trial_name                                            -> 'trial-1719873613'
validation_split_percentage                           -> 0.05

# Query The Feature Store

In [56]:
# feature_store_query = feature_group.athena_query()

In [57]:
# feature_store_table = feature_store_query.table_name

In [58]:
# query_string = """
# SELECT input_ids, input_mask, segment_ids, label_id, split_type  FROM "{}" WHERE split_type='train' LIMIT 5
# """.format(
#     feature_store_table
# )

# print("Running " + query_string)

In [59]:
# feature_store_query.run(
#     query_string=query_string,
#     output_location="s3://" + bucket + "/" + feature_store_offline_prefix + "/query_results/",
# )

# feature_store_query.wait()

In [60]:
# feature_store_query.as_dataframe()

# Show the Experiment Tracking Lineage

In [61]:
from sagemaker.analytics import ExperimentAnalytics

import pandas as pd

pd.set_option("max_colwidth", 500)
# pd.set_option("max_rows", 100)

experiment_analytics = ExperimentAnalytics(
    sagemaker_session=sess, experiment_name=experiment_name, sort_by="CreationTime", sort_order="Descending"
)

experiment_analytics_df = experiment_analytics.dataframe()
experiment_analytics_df

,TrialComponentName,DisplayName,SourceArn,AWS_DEFAULT_REGION,SageMaker.InstanceCount,SageMaker.InstanceType,SageMaker.VolumeSizeInGB,SageMaker.ImageUri - MediaType,SageMaker.ImageUri - Value,code - MediaType,...,raw-input-data - MediaType,raw-input-data - Value,bert-test - MediaType,bert-test - Value,bert-train - MediaType,bert-train - Value,bert-validation - MediaType,bert-validation - Value,Trials,Experiments
0,sagemaker-scikit-learn-2024-07-01-22-42-17-522-aws-processing-job,prepare,arn:aws:sagemaker:us-east-1:891377026966:processing-job/sagemaker-scikit-learn-2024-07-01-22-42-17-522,us-east-1,2.0,ml.t3.xlarge,30.0,None,683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3,None,...,None,s3://sagemaker-us-east-1-891377026966/amazon-reviews-pds/tsv/,None,s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test,None,s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train,None,s3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation,[trial-1719873613],[Amazon-Customer-Reviews-BERT-Experiment-1719873607]

In [62]:
trial_component_name = experiment_analytics_df.TrialComponentName[0]
print(trial_component_name)

sagemaker-scikit-learn-2024-07-01-22-42-17-522-aws-processing-job

In [63]:
trial_component_description = sm.describe_trial_component(TrialComponentName=trial_component_name)
trial_component_description

{'TrialComponentName': 'sagemaker-scikit-learn-2024-07-01-22-42-17-522-aws-processing-job',
 'TrialComponentArn': 'arn:aws:sagemaker:us-east-1:891377026966:experiment-trial-component/sagemaker-scikit-learn-2024-07-01-22-42-17-522-aws-processing-job',
 'DisplayName': 'prepare',
 'Source': {'SourceArn': 'arn:aws:sagemaker:us-east-1:891377026966:processing-job/sagemaker-scikit-learn-2024-07-01-22-42-17-522',
  'SourceType': 'SageMakerProcessingJob'},
 'Status': {'PrimaryStatus': 'Completed',
  'Message': 'Status: Completed, exit message: null, failure reason: null'},
 'StartTime': datetime.datetime(2024, 7, 1, 22, 47, 31, tzinfo=tzlocal()),
 'EndTime': datetime.datetime(2024, 7, 1, 23, 0, 41, tzinfo=tzlocal()),
 'CreationTime': datetime.datetime(2024, 7, 1, 22, 42, 18, 654000, tzinfo=tzlocal()),
 'CreatedBy': {'UserProfileArn': 'arn:aws:sagemaker:us-east-1:891377026966:user-profile/d-fu4acyc03cpg/default-20240628T190970',
  'UserProfileName': 'default-20240628T190970',
  'DomainId': 'd-fu4acyc03cpg'},
 'LastModifiedTime': datetime.datetime(2024, 7, 1, 23, 0, 42, 42000, tzinfo=tzlocal()),
 'LastModifiedBy': {},
 'Parameters': {'AWS_DEFAULT_REGION': {'StringValue': 'us-east-1'},
  'SageMaker.InstanceCount': {'NumberValue': 2.0},
  'SageMaker.InstanceType': {'StringValue': 'ml.t3.xlarge'},
  'SageMaker.VolumeSizeInGB': {'NumberValue': 30.0}},
 'InputArtifacts': {'SageMaker.ImageUri': {'Value': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3'},
  'code': {'Value': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/input/code/preprocess-scikit-text-to-bert-feature-store.py'},
  'raw-input-data': {'Value': 's3://sagemaker-us-east-1-891377026966/amazon-reviews-pds/tsv/'}},
 'OutputArtifacts': {'bert-test': {'Value': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-test'},
  'bert-train': {'Value': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-train'},
  'bert-validation': {'Value': 's3://sagemaker-us-east-1-891377026966/sagemaker-scikit-learn-2024-07-01-22-42-17-522/output/bert-validation'}},
 'Metrics': [],
 'LineageGroupArn': 'arn:aws:sagemaker:us-east-1:891377026966:lineage-group/sagemaker-default-lineage-group',
 'Sources': [],
 'ResponseMetadata': {'RequestId': '00ab83d9-1748-4f4b-8568-7e3cbe8de7de',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '00ab83d9-1748-4f4b-8568-7e3cbe8de7de',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '2031',
   'date': 'Mon, 01 Jul 2024 23:04:41 GMT'},
  'RetryAttempts': 0}}

# Show SageMaker ML Lineage Tracking 

Amazon SageMaker ML Lineage Tracking creates and stores information about the steps of a machine learning (ML) workflow from data preparation to model deployment. 

Amazon SageMaker Lineage enables events that happen within SageMaker to be traced via a graph structure. The data simplifies generating reports, making comparisons, or discovering relationships between events. For example easily trace both how a model was generated and where the model was deployed.

The lineage graph is created automatically by SageMaker and you can directly create or modify your own graphs.

## Key Concepts

* **Lineage Graph** - A connected graph tracing your machine learning workflow end to end.

* **Artifacts** - Represents a URI addressable object or data. Artifacts are typically inputs or outputs to Actions.

* **Actions** - Represents an action taken such as a computation, transformation, or job.

* **Contexts** - Provides a method to logically group other entities.

* **Associations** - A directed edge in the lineage graph that links two entities.

* **Lineage Traversal** - Starting from an arbitrary point trace the lineage graph to discover and analyze relationships between steps in your workflow.

* **Experiments** - Experiment entites (Experiments, Trials, and Trial Components) are also part of the lineage graph and can be associated wtih Artifacts, Actions, or Contexts.

## Show Lineage Artifacts For Our Processing Job

In [64]:
from sagemaker.lineage.visualizer import LineageTableVisualizer

lineage_table_viz = LineageTableVisualizer(sess)
lineage_table_viz_df = lineage_table_viz.show(processing_job_name=scikit_processing_job_name)
lineage_table_viz_df

,Name/Source,Direction,Type,Association Type,Lineage Type
0,s3://...ess-scikit-text-to-bert-feature-store.py,Input,DataSet,ContributedTo,artifact
1,s3://...t-1-891377026966/amazon-reviews-pds/tsv/,Input,DataSet,ContributedTo,artifact
2,68331...om/sagemaker-scikit-learn:0.23-1-cpu-py3,Input,Image,ContributedTo,artifact
3,s3://...2024-07-01-22-42-17-522/output/bert-test,Output,DataSet,Produced,artifact
4,s3://...7-01-22-42-17-522/output/bert-validation,Output,DataSet,Produced,artifact
5,s3://...024-07-01-22-42-17-522/output/bert-train,Output,DataSet,Produced,artifact

# Release Resources

In [65]:
%%html

<p><b>Shutting down your kernel for this notebook to release resources.</b></p>
<button class="sm-command-button" data-commandlinker-command="kernelmenu:shutdown" style="display:none;">Shutdown Kernel</button>
        
<script>
try {
    els = document.getElementsByClassName("sm-command-button");
    els[0].click();
}
catch(err) {
    // NoOp
}    
</script>

In [ ]:
%%javascript

try {
    Jupyter.notebook.save_checkpoint();
    Jupyter.notebook.session.delete();
}
catch(err) {
    // NoOp
}